# Generated by Django 3.2.9 on 2021-11-24 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('catchPhrase', models.CharField(max_length=200)),
                ('bs', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_geo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=50)),
                ('lng', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User_posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.our_users')),
            ],
        ),
        migrations.AddField(
            model_name='our_users',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blogs.user_company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_address',
            name='geo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blogs.user_geo'),
            preserve_default=False,
        ),
    ]
