# Generated by Django 3.2.9 on 2021-11-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20211124_2015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_address',
            new_name='Address',
        ),
        migrations.RenameModel(
            old_name='User_company',
            new_name='Company',
        ),
        migrations.RenameModel(
            old_name='User_geo',
            new_name='Geo',
        ),
    ]
