# Generated by Django 3.2.9 on 2021-11-24 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20211124_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='geo',
        ),
        migrations.RemoveField(
            model_name='our_users',
            name='address',
        ),
        migrations.RemoveField(
            model_name='our_users',
            name='company',
        ),
        migrations.AddField(
            model_name='address',
            name='our_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blogs.our_users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='our_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blogs.our_users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geo',
            name='addr',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blogs.address'),
            preserve_default=False,
        ),
    ]
