# Generated by Django 3.2.9 on 2021-11-25 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_rename_addr_geo_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='our_user',
            new_name='our_users',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='our_user',
            new_name='our_users',
        ),
    ]
