# Generated by Django 3.2.9 on 2021-11-23 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_our_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('suite', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User_geo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=128)),
                ('lng', models.CharField(max_length=128)),
                ('our_user_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.user_address')),
            ],
        ),
        migrations.AddField(
            model_name='our_users',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='our_users',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='our_users',
            name='website',
            field=models.URLField(default=''),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='user_address',
            name='our_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.our_users'),
        ),
    ]
