# Generated by Django 3.2.9 on 2021-11-23 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_user_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_address',
            old_name='our_user',
            new_name='address',
        ),
    ]
