# Generated by Django 3.2.9 on 2021-11-23 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_rename_our_user_user_address_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_address',
            name='address',
        ),
        migrations.AddField(
            model_name='our_users',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='polls.user_address'),
            preserve_default=False,
        ),
    ]
