# Generated by Django 3.2.9 on 2021-11-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20211123_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_users',
            name='company',
            field=models.JSONField(null=True),
        ),
    ]
