# Generated by Django 3.2.9 on 2021-11-24 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_user_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_posts',
            old_name='userid',
            new_name='userId',
        ),
    ]
